// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm78HEg_pfvh2v83aaVL1F_s1zkrPcJbY',
    appId: '1:223177952676:web:250c436bd7dc8cba2c8531',
    messagingSenderId: '223177952676',
    projectId: 'login-btl-e2aad',
    authDomain: 'login-btl-e2aad.firebaseapp.com',
    storageBucket: 'login-btl-e2aad.appspot.com',
    measurementId: 'G-4M1GVBYRPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-2QF0-xia46_78Huj0MrbURfgEgdp5C8',
    appId: '1:223177952676:android:57124feecb9dafa12c8531',
    messagingSenderId: '223177952676',
    projectId: 'login-btl-e2aad',
    storageBucket: 'login-btl-e2aad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfqmq5lwmhimNLzEnD-9i1RFG7iIL4kks',
    appId: '1:223177952676:ios:fac8b324a3e793772c8531',
    messagingSenderId: '223177952676',
    projectId: 'login-btl-e2aad',
    storageBucket: 'login-btl-e2aad.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfqmq5lwmhimNLzEnD-9i1RFG7iIL4kks',
    appId: '1:223177952676:ios:3c79f94c8cb5edb92c8531',
    messagingSenderId: '223177952676',
    projectId: 'login-btl-e2aad',
    storageBucket: 'login-btl-e2aad.appspot.com',
    iosBundleId: 'com.example.demo.RunnerTests',
  );
}
